### ISSUE TITLE
[BUG] Getting abort error while setting up cmt based cluster inside the DUT

### ISSUE THREAD

**Issue by sobintho** [intel/cluster-management-toolkit#23] opened 2024-02-14 03:57 UTC
Getting abort error while setting up cmtadm

gta@DUT7141ATSM:~/cluster-management-toolkit$ cmtadm prepare --control-plane dut7141atsm cluster1
Preparing cluster:

[Summary]

• Configuration:
        Cluster Name: cluster1
        Distribution: kubeadm
   Installed Version: <none>
          HTTP Proxy: http://proxy-chain.intel.com:911/ (/home/gta/.cmt/cmt.yaml)
          HTTP Proxy: http://proxy-chain.intel.com:911/ (Environment)
         HTTPS Proxy: http://proxy-chain.intel.com:912/ (/home/gta/.cmt/cmt.yaml)
         HTTPS Proxy: http://proxy-chain.intel.com:912/ (Environment)
            No Proxy: 127.0.0.1,localhost,intel.com (/home/gta/.cmt/cmt.yaml)
            No Proxy: localhost,.*.intel.com (Environment)

• Control Plane(s):
            Hostname: dut7141atsm (10.75.202.166)

Pending tasks (Dimmed tasks are either skipped or completed):

 0: Check for ssh host key and create if needed
 1: Add ssh keys for localhost, control plane(s) and nodes to /home/gta/.ssh/known_hosts
 2: Add public ssh keys to /home/gta/.ssh/authorized_keys
 3: Add public ssh keys to inventory
 4: Request the ansible password if necessary
 5: Install ansible.posix if necessary
 6: Run pre-prepare playbooks
 7: Run playbooks on localhost
 8: Run playbooks on hosts
 9: Run post-prepare playbooks

Start control plane preparation? [y/N]: y

[Preparing localhost and control plane(s)]
NOT OK; aborting.
gta@DUT7141ATSM:~/cluster-management-toolkit$

  runthis command cmtadm prepare --control-plane dut7141atsm cluster1

**Comment by taotriad** [comment] 2024-02-15 02:16
I have not been able to reproduce this, but I'll investigate this once I'm back at office.

**Comment by dweineha** [comment] 2024-02-23 14:06
This was caused by wrong ownership of the .ansible directory and too permissive rights for .netrc; both of these were fixed on the system in question, and cmt now has a check for .netrc permissions, as well as proper error messages in case something goes wrong during an Ansible jobs. I hope that's enough.

**Closed** 2024-03-10 13:31 UTC
Labels: bug
